### ISSUE TITLE
'tags' unsupported in tutum-phundament-eco

### ISSUE THREAD

**Issue by drsdre** [neam/docker-stack#5]
It looks like the 'tags' options in docker-compose.yml are not supported on docker-compose 1.1.0  in tutum-phundament-eco:

```
→ docker-compose up -d
Unsupported config option for db service: 'tags'
```

I'm guessing tags should be renamed to links.

**Comment by schmunk42** [comment]
Just remove the tag attributes as a workaround.
I'll create two stacks on for local and one for tutum.

Btw: What do you think about the name? Is it clear what it is from https://github.com/neam/docker-stack/issues/6#issuecomment-94457301 - or would something like `data-backend-stack` be more semantic?

**Comment by drsdre** [comment]
I expected 'tutum-phundament-eco' to be a development stack build for running on top of tutum (i.e. using tutum specific images). 'data-backend-stack' tells me that this stack should be run separate from a yii2 development stack. So yes, I would encourage the name change.

**Comment by schmunk42** [comment]
@drsdre Please have a look at: https://github.com/neam/docker-stack/tree/develop/stacks/phundament-eco

I added a stack for local usage.
